// <auto-generated />
namespace MicroSolutions.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newsettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newsettings));
        
        string IMigrationMetadata.Id
        {
            get { return "201712021825128_new-settings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
