// <auto-generated />
namespace MicroSolutions.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class customerfieldslengthsadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customerfieldslengthsadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201712021505375_customer-fields-lengths-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
