// <auto-generated />
namespace MicroSolutions.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addednewcolumntotrackchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addednewcolumntotrackchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201712030531262_added-new-column-to-track-changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
